// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz8QGtx_po5N35eYuxP9g3mhZ19PwwgHA',
    appId: '1:790952562441:web:996e97c26717b6ae7c8dd8',
    messagingSenderId: '790952562441',
    projectId: 'canteen-app-2105d',
    authDomain: 'canteen-app-2105d.firebaseapp.com',
    storageBucket: 'canteen-app-2105d.firebasestorage.app',
    measurementId: 'G-JQYTDXQMYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzVeaBaQcFRYvChXwG93aYHvfafl8UgSM',
    appId: '1:790952562441:android:a2fabf7cb853345b7c8dd8',
    messagingSenderId: '790952562441',
    projectId: 'canteen-app-2105d',
    storageBucket: 'canteen-app-2105d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV6x0GAFB3WbceGbK-8HWODQEaDgK1X6o',
    appId: '1:790952562441:ios:55fb734b2510a4277c8dd8',
    messagingSenderId: '790952562441',
    projectId: 'canteen-app-2105d',
    storageBucket: 'canteen-app-2105d.firebasestorage.app',
    iosBundleId: 'com.example.canteenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV6x0GAFB3WbceGbK-8HWODQEaDgK1X6o',
    appId: '1:790952562441:ios:55fb734b2510a4277c8dd8',
    messagingSenderId: '790952562441',
    projectId: 'canteen-app-2105d',
    storageBucket: 'canteen-app-2105d.firebasestorage.app',
    iosBundleId: 'com.example.canteenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz8QGtx_po5N35eYuxP9g3mhZ19PwwgHA',
    appId: '1:790952562441:web:0ec29e77d9c6b3ac7c8dd8',
    messagingSenderId: '790952562441',
    projectId: 'canteen-app-2105d',
    authDomain: 'canteen-app-2105d.firebaseapp.com',
    storageBucket: 'canteen-app-2105d.firebasestorage.app',
    measurementId: 'G-L7GE75PVVR',
  );
}
